<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>KKCharaStudioVRPlugin</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net35</TargetFramework>
    <KKGameDir Condition="'$(KKGameDir)' == ''">..\..\Koikatu3</KKGameDir>
    <LegacyLibDir Condition="'$(LegacyLibDir)' == ''">..\libs</LegacyLibDir>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>$(KKGameDir)\CharaStudio_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="VRGIN_KKCS">
      <HintPath>..\VRGIN_KKCS\bin\$(Configuration)\net35\VRGIN_KKCS.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(KKGameDir)\CharaStudio_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml">
      <HintPath>$(KKGameDir)\CharaStudio_Data\Managed\System.Xml.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>$(KKGameDir)\CharaStudio_Data\Managed\System.Core.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony_BepInEx4">
      <HintPath>$(LegacyLibDir)\0Harmony_BepInEx4.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(KKGameDir)\CharaStudio_Data\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="WindowsInput">
      <HintPath>$(KKGameDir)\BepInEx\WindowsInput.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(KKGameDir)\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(KKGameDir)\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="**/*.resx" />
    <EmbeddedResource Include="KKCharaStudioVR.Resource.resources" />
  </ItemGroup>
</Project>
