<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>VRGIN_KKCS</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net35</TargetFramework>
    <KKGameDir Condition="'$(KKGameDir)' == ''">..\..\Koikatu3</KKGameDir>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Core">
      <HintPath>$(KKGameDir)\CharaStudio_Data\Managed\System.Core.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(KKGameDir)\CharaStudio_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="LeapCSharp.NET3.5">
      <HintPath>$(KKGameDir)\BepInEx\LeapCSharp.NET3.5.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(KKGameDir)\CharaStudio_Data\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="WindowsInput">
      <HintPath>$(KKGameDir)\BepInEx\WindowsInput.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml">
      <HintPath>$(KKGameDir)\CharaStudio_Data\Managed\System.Xml.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml.Linq">
      <HintPath>$(KKGameDir)\CharaStudio_Data\Managed\System.Xml.Linq.dll</HintPath>
    </Reference>
    <Reference Include="SpeechTransport">
      <HintPath>$(KKGameDir)\BepInEx\SpeechTransport.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Remove="**/*.resx" />
    <EmbeddedResource Include="VRGIN.Resource.resources" />
  </ItemGroup>
</Project>
